### ISSUE TITLE
Can't run this application

### ISSUE THREAD

**Issue by fulalas** [pop-os/cosmic-settings-daemon#45]
When I try to run `cosmic-settings-daemon` I get this:

```
Error: InputOutput(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

Bulding in debug and enabling backtrace didn't provide any further information.

I'm testing current master on PorteuX (Slackware based), which has no systemd.

**Comment by mmstick** [comment]
This is started automatically by cosmic-session.
Make sure you have a reasonable max fd limit set for the cosmic-config inotify watchers.

**Comment by fulalas** [comment]
> This is started automatically by cosmic-session.

I know. Still, it doesn't work:

![error](https://github.com/user-attachments/assets/44168165-e209-4408-9192-872db16b62c7)

> Make sure you have a reasonable max fd limit set for the cosmic-config inotify watchers.

Not sure what you're talking about :(
