### ISSUE TITLE
Cosmic removes the .config/gtk-4.0 on every start on NixOS

### ISSUE THREAD

**Issue by RAVENz46** [pop-os/cosmic-settings-daemon#60]
From https://github.com/lilyinstarlight/nixos-cosmic/issues/257
I'm sorry if it is a NixOS-specific issue.
Regardless of whether 'Apply this theme to GNOME apps' on or off, `.config/gtk-4.0` was removed.

**Comment by Drakulix** [comment]
Ping @wash2

**Comment by wash2** [comment]
The settings daemon currently clears the gtk.css file after it starts if the setting for exporting the theme to gtk is disabled. I guess it could move it to a backup file instead if it wasn't from cosmic.

**Comment by RAVENz46** [comment]
> The settings daemon currently clears the gtk.css file after it starts if the setting for exporting the theme to gtk is disabled. I guess it could move it to a backup file instead if it wasn't from cosmic.

Then, it is impossible to use own gtk.css instead of made-by-cosmic one?

**Comment by mmstick** [comment]
If you want to use a custom gtk.css, you must disable GNOME theme integrations in COSMIC. COSMIC uses gtk.css for the same reason you are. GTK theme integration.
